chore: updated RouterLink constructor call argument
vaadin/bakery-app-starter-flow-spring pull request #1184
Opened 2022-08-04 08:10 UTC by MarcinVaadin

## Description

Updated RouterLink constructor method call argument to avoid ambiguity errors

Fixes: #1183

Relates to: https://github.com/vaadin/flow/issues/14143

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-08-04 08:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/bakery-app-starter-flow-spring?pullRequest=1184) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/bakery-app-starter-flow-spring?pullRequest=1184) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/bakery-app-starter-flow-spring?pullRequest=1184) it.</sub>

2022-08-05 09:38 UTC, mshabarov requested changes

2022-08-05 09:38 UTC, mshabarov commented on src/main/java/com/vaadin/starter/bakery/ui/MainView.java
> +		return createTab(populateLink(new RouterLink("", viewClass), icon, title));
Why not use `RouterLink(Class<? extends Component> navigationTarget)` without a text parameter. I think it was exactly the idea of the implemented feature - avoid text parameter. So `new RouterLink(viewClass)` should be fine.

2022-08-05 09:40 UTC, mshabarov commented on src/main/java/com/vaadin/starter/bakery/ui/MainView.java
> +		return createTab(populateLink(new RouterLink("", viewClass), icon, title));
Or, well, this code is used with both v23.1 and v23.2...then it's fine.

2022-08-05 09:49 UTC, mshabarov commented on src/main/java/com/vaadin/starter/bakery/ui/MainView.java
> +		return createTab(populateLink(new RouterLink("", viewClass), icon, title));
I propose to use `new RouterLink(viewClass)`, but keep this PR before we bump the Vaadin version in the project to 23.2.0.

2022-08-05 12:33 UTC, MarcinVaadin commented on src/main/java/com/vaadin/starter/bakery/ui/MainView.java
> +		return createTab(populateLink(new RouterLink("", viewClass), icon, title));
I left it like that intentionally to be able to check if no errors are present after updating Flow dependency.

2022-08-05 12:41 UTC, mshabarov commented on src/main/java/com/vaadin/starter/bakery/ui/MainView.java
> +		return createTab(populateLink(new RouterLink("", viewClass), icon, title));
Most likely there wouldn't be any issues because now the type is string and the constructor has a certain match.
But the thing is that exposing the code in this starter, we recommend developers to use Vaadin in the same manner. So I would better recommend them to use `new RouterLink(viewClass)`, if they don't need a text :)

2022-08-05 13:43 UTC, mshabarov approved these changes

2022-08-05 13:44 UTC, merged