chore: GitHub Workflows security hardening
vaadin/bakery-app-starter-flow-spring pull request #1194
Opened 2022-09-19 12:43 UTC by ZheSun88

## Description

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or action) is restricted. It is recommended to have [most strict permissions on the top level](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions) and grant write permissions on [job level](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) case by case.

reference commit in https://github.com/vaadin/flow/pull/14463

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-09-19 12:51 UTC, manolo requested changes

2022-09-19 12:51 UTC, manolo commented on .github/workflows/validation.yml
> +    permissions:
Not needed in bakery

2022-09-19 12:56 UTC, ZheSun88 commented on .github/workflows/validation.yml
> +    permissions:
are you sure this is not needed? the plugin has been used here https://github.com/vaadin/bakery-app-starter-flow-spring/blob/v23/.github/workflows/validation.yml#L38

2022-09-20 06:21 UTC, manolo approved these changes

2022-09-20 06:21 UTC, merged